[package]
name = "kosu"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-deque = "0.8"
crossterm = "0.29"
libc = "0.2"
kou-ui = { path = "kou-ui/crates/kou-ui", features = ["tui"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Wdk_Storage_FileSystem",
    "Wdk_Foundation",
] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
